### ISSUE TITLE
[enhancement] 支持指定目录

### ISSUE THREAD

**Issue by aladdin-add** [xcatliu/cqc#9]
e.g.
```bash
cqc ./lib
```
(?)默认ext: `.js`

**Comment by xcatliu** [comment]
这样的话，两种模式的冲突不是很好解决，比如：

`src` 目录下有 `src/index.css`, `src/js/index.js`

如果我只想检查 `src` 目录下的所有文件，并不想递归的检查多级目录下的其他文件，该怎么设计脚本呢？

---

```shell
cqc ./src/*
```

执行上面的命令之后，可能预期只是想检查 `src` 目录下的所有文件，但是却检查到了所有的多级目录下的 js 文件

**Comment by aladdin-add** [comment]
`cqc "./src/*.js"`就可以啊。

感觉大多数的工具都是默认递归的。有例外就是像mocha这样的，需要指定参数`--recursive`

**Comment by xcatliu** [comment]
`cqc .src/*.js` 有两个问题：

1. 如果不确定后缀的话，就不能这么用了
2. 如果有个文件夹是以 `.js` 结尾的，就还是变成了递归的检查了

**Comment by xcatliu** [comment]
比如执行

```shell
cqc src/**/*.css
```

结果有个文件夹叫 `normalize.css`，就会把它内部的 `js` 文件也检查了

**Comment by aladdin-add** [comment]
恩，确实有冲突。

我觉的最常规的需求：检查src目录下所有文件，现在需要`cqc src/**/*.js src/**/*.jsx`不是很方便。可不可以直接执行 `cqc src`？

其它的可以通过参数来筛选。e.g. `--ext .js`, `--no-recusive`

**Comment by xcatliu** [comment]
嗯确实最常规的需求是检查 `src` 目录下的所有文件。

如果按照你的那个设计，还有一个问题，如果执行：

```shell
cqc src/**/page
```

`src` 下有以下文件 `src/page/index.js`, `src/foo/page/index.js`, `src/bar/page`，其中 `src/bar/page` 是一个文件，不是一个目录，那么该不该检查 `src/bar/page` 呢？

**Comment by aladdin-add** [comment]
这种情况不太常见，我稍微倾向于不检查：
* 默认`--ext .js`，`src/bar/page`算是匹配失败
* `src/bar/page`文件类型不确定，应该按 js/css 检查？

**Comment by aladdin-add** [comment]
> 比如执行
> 
> cqc src/**/*.css
> 结果有个文件夹叫 normalize.css，就会把它内部的 js 文件也检查了

这种情况感觉等同于：`cqc --ext .css src`，不应该检查js文件啊

**Comment by xcatliu** [comment]
> 这种情况感觉等同于：`cqc --ext .css src`，不应该检查js文件啊

并不是啊，如果匹配到一个目录了，就应该去递归的找目录下的符合 --ext 的文件呀

**Comment by xcatliu** [comment]
可以这样子设计？

- 如果传入的是一个确定的（即不包含 * 的）路径，则判断它是否是一个目录
  - 若是一个目录，则递归按照 --ext 查找
  - 若是一个文件，则匹配这个文件
- 如果传入的是一个 pattern（即包含 *），则按原有的 cqc 逻辑走

**Comment by aladdin-add** [comment]
<del>`cqc src/**/*.css` 这种情况，我觉得只匹配css文件更合理一些，你觉得呢？</del>

哦，这就是原来的逻辑啊。 👍

**Comment by xcatliu** [comment]
我刚刚说的设计还是有个问题，它无法实现匹配多个目录了，只能传入一个目录

**Comment by aladdin-add** [comment]
如果传入的是一个确定的（即不包含 * 的）路径，则判断它是否是一个目录：
1. 若是一个文件，则匹配这个文件
2. 若是一个目录，则递归按照 --ext 查找
3. 加上指定的后缀(--ext=js foo => foo.js), 如果文件存在，匹配成功

如果传入的是一个 pattern（即包含 *）：
1. 如果最后为`**/*.ext`，视为指定`--ext`，去掉该后缀 => 递归
2. 没想清楚。。。 😹

**Comment by xcatliu** [comment]
自动补 `.js` 和自动去掉 `.ext` 太反人类了。。。

**Comment by aladdin-add** [comment]
我觉得这种特别常用的，肯定有专门的lib去做这种事哈，应该不用自己处理的，就像gitignore那样就行

**Comment by xcatliu** [comment]
- 如果传入的是 ***一个*** 参数
  - 如果是一个确定的（即不包含 * 的）路径
    - 若是一个目录，则递归按照 --ext 查找
    - 若是一个文件，则匹配这个文件
  - 如果是一个 pattern（即包含 *），则按原有的 cqc 逻辑走
- 如果传入的是多个参数，则按原有的 cqc 逻辑走

这样的话，除了只能指定一个目录以外，没有其他缺点了

**Comment by aladdin-add** [comment]
只能指定一个目录才反人类呢！！！

**Comment by xcatliu** [comment]
还有个方案是 `cqc --input-dir="src,lib" --ext="js,jsx"`
通过一个参数告诉 cqc 是按目录读取还是按 pattern 读取

这样就可以实现输入多个目录了

**Comment by aladdin-add** [comment]
大神已经帮你写好了哇！https://github.com/isaacs/minimatch

**Comment by xcatliu** [comment]
我用的 https://github.com/sindresorhus/globby 就是依赖了 https://github.com/isaacs/node-glob which 依赖了 https://github.com/isaacs/minimatch 的

**Comment by xcatliu** [comment]
@Aladdin-ADD 已添加对输入目录的支持：

```bash
cqc src lib --ext=.js,.jsx
```

**Comment by xcatliu** [comment]
有测试改起来就是安心😁

**Comment by aladdin-add** [comment]
Note: --ext is only used when the arguments are directories. If you use glob patterns or file names, then --ext is ignored.

**Comment by xcatliu** [comment]
Updated
